version: "3.9"

services:
  db:
    image: postgres
    container_name: mydb
    environment:
      POSTGRES_USER: 21savgae
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  main:
    build: ./app/main  # здесь путь к твоему Dockerfile для Go
    image: main:latest
    container_name: main
    depends_on:
      - db
   
    ports:
      - ":8080"

  nginx:
    build: ./app/nginx  # здесь путь к Dockerfile nginx
    container_name: nginx
    depends_on:
      - main
    ports:
      - "80:80"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/conf.d:ro

volumes:
  pg_data:
