version: "3.9"

services:
  db:
    image: postgres
    container_name: mydb
    environment:
      POSTGRES_USER: 21savage
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - daun-net

  main:
    build: ./app/main  
    image: main:latest
    container_name: main
    depends_on:
      - db
    volumes:
      - /home/savage21/hardWork/go/ci_cd/app/main:/app/main
    ports:
      - ":80"
    networks:
      - daun-net

  nginx:
    build: ./app/nginx  
    container_name: nginx
    depends_on:
      - main
    ports:
      - "80:80"
   
    networks:
      - daun-net

networks:
  daun-net:
    driver: bridge
volumes:
  pg_data:
