name: test pipeline

on:
  push:
    branches:
      - dev
    paths:
      - "app/**"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: hello world
      run: echo "hello world"
