name: main-test pipeline

on:
  push:
    branches:
      - dev
    paths:
      - "app/**"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker compose up -d --build
    - name: Tests
      run: docker exec main go test ./...
    
