# This is a basic workflow to help you get started with Actions

name: deploy main

# Controls when the workflow will run
on:
  workflow_run:
    workflows:  ["main test"]
    types:
      - completed
    branches:
      - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: build image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USER}}/main:latest ./app/main

      # Runs a set of commands using the runners shell
      - name: docker hub connect
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push ${{secrets.DOCKERHUB_USER}}/main:latest
      - name: deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker compose pull
            docker compose up -d
            docker image prune -f
        
       
