name: CI/CD

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  test:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose -f main/docker-compose.yml up -d --build
          docker exec main go test ./...
      - run: docker compose -f main/docker-compose.yml down

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "✅ Tests passed. Starting deployment..."
          # твои команды деплоя
